# Generated by Django 6.0.1 on 2026-01-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltycard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loyaltycard',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('loyalty', 'loyalty'), ('order', 'order'), ('expire', 'expire')], max_length=20),
        ),
    ]
