# Generated by Django 6.0.1 on 2026-01-16 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_remove_loyaltycard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('order', 'Order Bonus'), ('manual', 'Manual Bonus'), ('expire', 'Expired')], max_length=20),
        ),
    ]
